server:
  port: 8083

spring:
  application:
    name: nacos-consumer
  cloud:
    discovery:
      server-addr: 127.0.0.1:8848

# 消费者将要去访问的微服务的名称
service-url:
  nacos-user-service: http://nacos-provider


